import Head from "next/head";
import {PropsWithChildren} from "react";
import Navbar from "@/components/Navbar/Navbar";
import {Montserrat} from "next/font/google";


const font = Montserrat({
    weight: ["700"],
    subsets: ["latin", "cyrillic"],
});

export default function Layout({children}: PropsWithChildren) {
    return <>
        <Head>
            <title>Book shop</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <div className={font.className}>
            <header>
                <Navbar/>
            </header>
            <main>
                {children}
            </main>
        </div>
    </>;
}